PAM/Controllers/IMDBItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PAM.Data;
using PAM.Models;

namespace PAM.Controllers
{
    public class IMDBItemsController : Controller
    {
        private readonly PAMContext _context;
        private readonly ViewBagImageController _viewBagImageController;

        public IMDBItemsController(PAMContext context)
        {
            _context = context;
            _viewBagImageController = new ViewBagImageController(_context);
        }

        // GET: IMDBItems
        public async Task<IActionResult> Index()
        {
            ViewBag.imgsrc = _viewBagImageController.SetViewBagImage(User);
            return View(await _context.IMDBItem.ToListAsync());
        }

        // GET: IMDBItems/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            ViewBag.imgsrc = _viewBagImageController.SetViewBagImage(User);
            if (id == null)
            {
                return NotFound();
            }

            var iMDBItem = await _context.IMDBItem
                .FirstOrDefaultAsync(m => m.IMDBItemID == id);
            if (iMDBItem == null)
            {
                return NotFound();
            }

            return View(iMDBItem);
        }

        // GET: IMDBItems/Create
        public IActionResult Create()
        {
            ViewBag.imgsrc = _viewBagImageController.SetViewBagImage(User);
            return View();
        }

        // POST: IMDBItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IMDBItemID,Awards,ContentRating,IMDBRating,IMDBID,ImageLink,MetacriticRating,Plot,Runtime,Title,TrailerLink,Type,Year")] IMDBItem iMDBItem)
        {
            ViewBag.imgsrc = _viewBagImageController.SetViewBagImage(User);
            if (ModelState.IsValid)
            {
                _context.Add(iMDBItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(iMDBItem);
        }

        // GET: IMDBItems/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.imgsrc = _viewBagImageController.SetViewBagImage(User);
            if (id == null)
            {
                return NotFound();
            }

            var iMDBItem = await _context.IMDBItem.FindAsync(id);
            if (iMDBItem == null)
            {
                return NotFound();
            }
            return View(iMDBItem);
        }

        // POST: IMDBItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IMDBItemID,Awards,ContentRating,IMDBRating,IMDBID,ImageLink,MetacriticRating,Plot,Runtime,Title,TrailerLink,Type,Year")] IMDBItem iMDBItem)
        {
            ViewBag.imgsrc = _viewBagImageController.SetViewBagImage(User);
            if (id != iMDBItem.IMDBItemID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(iMDBItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IMDBItemExists(iMDBItem.IMDBItemID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(iMDBItem);
        }

        // GET: IMDBItems/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            ViewBag.imgsrc = _viewBagImageController.SetViewBagImage(User);
            if (id == null)
            {
                return NotFound();
            }

            var iMDBItem = await _context.IMDBItem
                .FirstOrDefaultAsync(m => m.IMDBItemID == id);
            if (iMDBItem == null)
            {
                return NotFound();
            }

            return View(iMDBItem);
        }

        // POST: IMDBItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            ViewBag.imgsrc = _viewBagImageController.SetViewBagImage(User);
            var iMDBItem = await _context.IMDBItem.FindAsync(id);
            _context.IMDBItem.Remove(iMDBItem);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool IMDBItemExists(int id)
        {
            ViewBag.imgsrc = _viewBagImageController.SetViewBagImage(User);
            return _context.IMDBItem.Any(e => e.IMDBItemID == id);
        }
    }
}

PAM/Controllers/UsersController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PAM.Data;
using PAM.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace PAM.Controllers
{
    public class UsersController : Controller
    {
        private readonly PAMContext _context;
        private readonly ViewBagImageController _viewBagImageController;
        public UsersController(PAMContext context)
        {
            _context = context;
            _viewBagImageController = new ViewBagImageController(_context);
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                string currentUserGoogleIdentifier = User.Claims
                    .Where(c => c.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier")
                    .Select(c => c.Value)
                    .FirstOrDefault();

                string googleIdentifier = _context.User
                    .Where(user => user.GoogleUserID == currentUserGoogleIdentifier)
                    .Select(user => user.GoogleUserID)
                    .FirstOrDefault();

                if (googleIdentifier == null)
                {
                    string userName = User.Claims
                        .Where(c => c.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname")
                        .Select(c => c.Value)
                        .FirstOrDefault();
                    _context.Add(new User
                    {
                        GoogleUserID = currentUserGoogleIdentifier,
                        UserName = userName,
                        Photo = null
                    });
                    await _context.SaveChangesAsync();
                }
            }
            ViewBag.imgsrc = _viewBagImageController.SetViewBagImage(User);
            return View(await _context.User.ToListAsync());
        }

        [Authorize]
        public async Task<IActionResult> EditProfile(string? googleId)
        {
            ViewBag.imgsrc = _viewBagImageController.SetViewBagImage(User);
            if (googleId == null)
            {
                return NotFound();
            }
            string googleCurrentUserId = User.Claims
                .Where(c => c.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier")
                .Select(c => c.Value)
                .FirstOrDefault();
            if(googleCurrentUserId != googleId)
            {
                Redirect("/Account/Denied");
            }
            var user = await _context.User
                .FirstOrDefaultAsync(m => m.GoogleUserID == googleId);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }


        [HttpPost][Authorize]
        public async Task<IActionResult> EditProfile(IFormFile photo, string userName)
        {
            ViewBag.imgsrc = _viewBagImageController.SetViewBagImage(User);
            string googleId = User.Claims
                .Where(c => c.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier")
                .Select(c => c.Value)
                .FirstOrDefault();
            var user = await _context.User
                .FirstOrDefaultAsync(m => m.GoogleUserID == googleId);
            if(user == null)
            {
                return NotFound();
            }
            user.UserName = userName;
            using(var target = new MemoryStream())
            {
                if(photo != null)
                {
                    photo.CopyTo(target);
                    user.Photo = target.ToArray();
                }
            }

            _context.SaveChanges();
            return View(user);
        }


        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            ViewBag.imgsrc = _viewBagImageController.SetViewBagImage(User);
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.UserID == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            //_viewBagImage.SetViewBagImage();
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserID,GoogleUserID,UserName,Photo")] User user)
        {
            ViewBag.imgsrc = _viewBagImageController.SetViewBagImage(User);
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.imgsrc = _viewBagImageController.SetViewBagImage(User);
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserID,GoogleUserID,UserName,Photo")] User user)
        {
            ViewBag.imgsrc = _viewBagImageController.SetViewBagImage(User);
            if (id != user.UserID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.UserID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            ViewBag.imgsrc = _viewBagImageController.SetViewBagImage(User);
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.UserID == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            ViewBag.imgsrc = _viewBagImageController.SetViewBagImage(User);
            var user = await _context.User.FindAsync(id);
            _context.User.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            ViewBag.imgsrc = _viewBagImageController.SetViewBagImage(User);
            return _context.User.Any(e => e.UserID == id);
        }
    }
}

PAM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head class="bg-dark">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PAM</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="text-white bg-dark">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-secondary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">PAM</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Peliculas">Peliculas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Anime">Anime</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Videojuegos">Videojuegos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Users" asp-action="">Usuarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="IMDBItems" asp-action="">IMDBItems</a>
                        </li>
                    </ul>
                    @{
                        if (User.Identity.IsAuthenticated)
                        {
                            string googleId = User.Claims
                                .Where(c => c.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier")
                                .Select(c => c.Value)
                                .FirstOrDefault();

                            <div class="dropdown show">
                                <a class="" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <img src="@ViewBag.imgsrc" width="50" height="50" class="rounded-circle"/>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <a class="dropdown-item" asp-controller="Users" asp-action="EditProfile" asp-route-googleId="@googleId">
                                        Editar Perfil
                                    </a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Logout">Cerrar Sesion</a>
                                </div>
                            </div>
                        }
                        else
                        {
                            <a class="btn btn-info my-2 my-sm-0" asp-area="" asp-controller="Account" asp-action="Login">Iniciar sesion</a>
                        }
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PAM
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>